### ISSUE TITLE
Grupo de Laravel está lotado

### ISSUE THREAD

**Issue by alande-amorim** [cleversonferreira/whatsapp-groups#1]
Não consigo acessar o grupo de Laravel pois está lotado.
Existe outro grupo para Whatsapp ou para Telegram?

**Comment by cleversonferreira** [comment]
Olá, Alande
Realmente não conheço outro grupo de Laravel, mas aconselho a continuar tentando, sempre um membro ou outro acaba saindo.
Caso eu encontre algum, atualizarei a lista, e te informarei.
