### ISSUE TITLE
Links Revogados

### ISSUE THREAD

**Issue by Scemist** [cleversonferreira/whatsapp-groups#2]
Opa, a maioria está revogada. Poderia fazer um limpa, adicionar novos links. É legal a ideia de divulgar comunidades de desencolcedores no WhatsApp. Se pudermos achar mais colaboradores.

**Comment by cleversonferreira** [comment]
Opa @Scemist , fique a vontade para enviar um merge request, no momento não consigo fazer o teste, mas sua ajuda seria muito boa para o repositório.
